name: Test Dev
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - development
    types:
      - closed
jobs:
  terraform_plan_dev:
    name: Terraform Plan - Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Terraform Plan
        run: |
          cd dev
          echo "TEST SUCCESS"


